table moedas
	lineageTag: fe4ced72-9c09-4a18-a4c8-9c402c41ba77

	column Moeda
		dataType: string
		lineageTag: 99712ab4-a657-4aa4-a328-d574af509dad
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: e0934bf3-0da7-4562-92e5-3fcfd7fb8838
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		lineageTag: 1a91397d-6ff0-4dad-b2c6-ae37d7daadc9
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition moedas = m
		mode: import
		queryGroup: Dimensoes
		source = ```
				let
				    source = Table.FromRows(
				        {
				            {"BRL", "Real brasileiro", "R$ #,##0.00;R$ #,##0.00;-"},
				            {"AUD", "Dólar australiano", "$ #,##0.00;$ #,##0.00;-"},
				            {"CAD", "Dólar canadense", "$ #,##0.00;$ #,##0.00;-"},
				            {"CHF", "Franco suíço", "Fr #,##0.00;Fr #,##0.00;-"},
				            {"DKK", "Coroa dinamarquesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"EUR", "Euro", "€ #,##0.00;€ #,##0.00;-"},
				            {"GBP", "Libra Esterlina", "£ #,##0.00;£ #,##0.00;-"},
				            {"JPY", "Iene", "¥ #,##0;¥ #,##0;-"},
				            {"NOK", "Coroa norueguesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"SEK", "Coroa sueca", "kr #,##0.00;kr #,##0.00;-"},
				            {"USD", "Dólar dos Estados Unidos", "$ #,##0.00;$ #,##0.00;-"}
				        },
				        {"Moeda", "Nome", "Formato"}
				    ),
				    
				    changedType = Table.TransformColumnTypes(
				        source,{
				            {"Moeda", type text}, 
				            {"Nome", type text}, 
				            {"Formato", type text}
				        }
				    )
				
				in
				    changedType
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

